webapp/blueprints/main/models.py
from datetime import datetime
from webapp import db


class Card(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_board = db.Column(db.Integer, db.ForeignKey('board.id'), nullable=False)
    creat = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    modificat = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    title = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text)
    image = db.Column(db.Text)

    def __repr__(self):
        return f'''Card({self.id}, {self.id_board}, "{self.title}", "{self.description}", "{self.image}")'''


class Board(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    # id_user = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    creat = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    modificat = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    title = db.Column(db.Text, nullable=False)

    cards = db.relationship("Card", backref=db.backref('board', lazy=True), lazy=True)

    def __repr__(self):
        return f'''Board({self.id}, "{self.title}")'''


webapp/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired

from wtforms import (
    StringField,
    SelectField,
    SubmitField,
)

from flask_wtf.file import (
    FileField,
    FileAllowed
)


class Form_Card(FlaskForm):
    id_board = SelectField('Board', coerce=int, validators=[InputRequired()])
    title = StringField('Title', validators=[InputRequired()])
    description = StringField('Description')
    image = FileField('Image', validators=[FileAllowed(['jpg', 'png']), InputRequired()])

    submit = SubmitField('Add')


class Form_Board(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    submit = SubmitField('Add')


webapp/blueprints/main/routes.py
import os
import secrets

from flask_login import login_required
from sqlalchemy import exc

from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    Blueprint,
    session,
    jsonify
)

from webapp import (
    db,
    logging
)

from webapp.blueprints.main.forms import (
    Form_Card,
    Form_Board
)

from webapp.blueprints.main.models import (
    Board,
    Card
)

from webapp.blueprints.main.utils import iter_pages

main = Blueprint('main', __name__, template_folder='templates', static_folder='static', static_url_path='/static')


def save_file(form_file):
    if form_file:
        _, extension = os.path.splitext(form_file.filename)
        file_name = secrets.token_hex(8) + extension
        while file_name in os.listdir(os.path.join(main.root_path, 'static/assets/image')):
            file_name = secrets.token_hex(8) + extension

        if extension in ('.jpg', '.png'):
            file_path = os.path.join(main.root_path, 'static/assets/image', file_name)

        form_file.save(file_path)

        return file_name
    else:
        return ''


@main.route("/edit_card/<int:id>", methods=['GET', 'POST'])
@main.route('/create_card', methods=['GET', 'POST'])
@login_required
def create_card(id=None):
    form = Form_Card()
    form.id_board.choices = [(row.id, row.title) for row in Board.query.all()]

    if id:
        card = Card.query.get_or_404(id)

    # get values from parameters if available
    if request.method == 'GET':
        form.process(request.args)
        form.id_board.data = session.get('board', Board.query.first().id)

        if id:
            form.id_board.data = card.id_board
            form.title.data = card.title
            form.description.data = card.description
            form.image.data = card.image

    if form.validate_on_submit():
        try:
            if id:
                card.id_board = form.id_board.data
                card.title = form.title.data
                card.description = form.description.data
                card.image = save_file(form.image.data)

                db.session.commit()

                flash('Done!', 'success')
                return redirect(url_for('main.card', id=card.id))
            else:
                row = Card(
                    id_board=form.id_board.data,
                    title=form.title.data,
                    description=form.description.data,
                    image=save_file(form.image.data))
                db.session.add(row)
                db.session.commit()

                flash('Done!', 'success')
        except exc.IntegrityError as e:
            flash(f'Error: {e}', 'danger')

    return render_template(
        f'create_card.html',
        title='Create a card',
        form=form)


@main.route('/edit_board/<int:id>', methods=['GET', 'POST'])
@main.route('/create_board', methods=['GET', 'POST'])
@login_required
def create_board(id=None):
    form = Form_Board()

    if id:
        board = Board.query.get_or_404(id)

    # get values from parameters if available
    if request.method == 'GET':
        form.process(request.args)
        if id:
            form.title.data = board.title

    if form.validate_on_submit():
        try:
            if id:
                board.title = form.title.data
                db.session.commit()

                return redirect(url_for('main.board', id=id))
                flash('Done!', 'success')
            else:
                row = Board(title=form.title.data)
                db.session.add(row)
                db.session.commit()

                return redirect(url_for('main.board', id=row.id))
                flash('Done!', 'success')
        except exc.IntegrityError as e:
            flash(f'Error: {e}', 'danger')

    return render_template(
        f'create_board.html',
        title='Create a board',
        form=form)


@main.route('/board/<int:id>', methods=['GET', 'POST'])
@login_required
def board(id):
    session['board'] = id
    page = request.args.get('page', 1, type=int)
    board = Board.query.get_or_404(id)
    cards = Card.query.filter_by(board=board)\
        .paginate(per_page=10, page=page)

    return render_template(
        f'board.html',
        title='Create a board',
        data=cards,
        board=board,
        page=page)


@main.route("/card/<int:id>")
def card(id):
    session['card'] = id
    card = Card.query.get_or_404(id)
    return render_template(
        'card.html',
        title=card.title,
        card=card)


@main.route('/', methods=['GET', 'POST'])
@main.route("/boards")
def boards():
    page = request.args.get('page', 1, type=int)
    return render_template(
        'boards.html',
        title='Boards',
        data=Board.query.paginate(per_page=10, page=page))


@main.route("/delete_board/<int:id>")
def delete_board(id):
    board = Board.query.get_or_404(id)
    for card in board.cards:
        db.session.delete(card)

    db.session.delete(board)
    db.session.commit()

    return redirect(url_for('main.boards'))


@main.route("/delete_card/<int:id>")
def delete_card(id):
    card = Card.query.get_or_404(id)
    db.session.delete(card)
    db.session.commit()

    return redirect(url_for('main.board', id=session.get('board')))



webapp/blueprints/main/templates/board.html
{% extends "layout.html" %}
{% block content %}
	<h3>{{ board.title }}</h3>
	<hr>

	{% for row in data.items %}
		<a href="{{ url_for('main.card', id=row.id) }}">{{ row.title }}</a>
		<hr>
	{% endfor %}
    <br>

    {% for page in pages %}
        {% if page %}
            {% if data.page == page %}
                <a href="{{ url_for('main.board', id_board=id_board, page=page) }}" class="btn btn-info md-1">{{ page }}</a>
            {% else %}
                <a href="{{ url_for('main.board', id_board=id_board, page=page) }}" class="btn btn-outline-info md-1">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
	<a class="btn btn-success" href="{{ url_for('main.create_card') }}">Create Card</a>
	<a class="btn btn-info" href="{{ url_for('main.create_board', id=session.get('board')) }}">Edit Board</a>
{% endblock content %}

webapp/blueprints/main/templates/boards.html
{% extends "layout.html" %}
{% block content %}
	{% for row in data.items %}
		<a href="{{ url_for('main.board', id=row.id) }}">{{ row.title }}</a>
		<hr>
	{% endfor %}
    <br>

    {% for page in pages %}
        {% if page %}
            {% if data.page == page %}
                <a href="{{ url_for('main.board', page=page) }}" class="btn btn-info md-1">{{ page }}</a>
            {% else %}
                <a href="{{ url_for('main.board', page=page) }}" class="btn btn-outline-info md-1">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
	<a class="btn btn-success" href="{{ url_for('main.create_board') }}">Create Board</a>
{% endblock content %}

webapp/blueprints/main/templates/card.html
{% extends "layout.html" %}
{% block content %}
	<h3>{{ card.title }}</h3>
	<p>{{ card.description }}</p>

	{% if card.image %}
		<hr>
		<img src="{{ url_for('main.static', filename='assets/image/' + card.image) }}">
	{% endif %}

	<hr>

	<a class="btn btn-info" href="{{ url_for('main.create_card', id=card.id) }}">Edit</a>
	<a class="btn btn-danger" href="{{ url_for('main.delete_card', id=card.id) }}">Delete</a>
{% endblock content %}

webapp/blueprints/main/templates/create_board.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4"><!-- empty space --></div>

    <div class="content-section col-md-4">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom md-4">{{ title }}</legend>

            <div class="form-group"> <!-- INPUT: title -->
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group"> <!-- SUBMIT BUTTON -->
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>

    <div class="col-md-4"><!-- empty space --></div>
</div>
{% endblock content %}

webapp/blueprints/main/templates/create_card.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4"><!-- empty space --></div>

    <div class="content-section col-md-4">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom md-4">{{ title }}</legend>

            <div class="form-group"> <!-- INPUT: board -->
				{{ form.id_board.label(class="form-control-label") }}
				{{ form.id_board(class="form-control form-control-lg") }}
            </div>

            <div class="form-group"> <!-- INPUT: title -->
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group"> <!-- INPUT: description -->
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group"> <!-- INPUT: IMAGE -->
				{{ form.image.label() }}
				{{ form.image(class="form-control-file") }}
				{% for error in form.image.errors %}
					<span class="text-danger">{{ error }}</span><br>
				{% endfor %}
            </div>
        </fieldset>

        <div class="form-group"> <!-- SUBMIT BUTTON -->
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>

    <div class="col-md-4"><!-- empty space --></div>
</div>
{% endblock content %}

webapp/blueprints/main/templates/senzor.html
<!-- Take photo -->
<input id="file" name="file" type="file" accept="image/*" capture="camera" />


<!-- Vibrate -->
<script>
alert('vibrate')
var vibrate = navigator.vibrate || navigator.mozVibrate;
vibrate(1000);
vibrate([1000, 500, 2000]);
</script>